services:
  tfl-discord-bot:
    image: tfl-discord-bot
    container_name: tfl-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - 6942:6942
